---
- hosts: addresses
  gather_facts: true
  roles:
    - role: prereq
      become: true

- hosts: basics
  gather_facts: true
  roles:
    - role: node_exporter
      become: true
    - role: cgroupv2
      become: true
    - role: firewalld
      become: true

- hosts: worker-nodes-basics
  gather_facts: true
  roles:
    - role: packages
    - role: systemctl
      become: true

- hosts: gpu-passthrough
  gather_facts: true
  roles:
    - role: gpupassthrough
      become: true