---
- name: Enable libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Enable libvirtd.socket
  ansible.builtin.systemd:
    name: libvirtd.socket
    enabled: yes
    state: started

- name: Enable libvirtd-ro.socket
  ansible.builtin.systemd:
    name: libvirtd-ro.socket
    enabled: yes
    state: started

- name: Enable system podman
  ansible.builtin.systemd:
    name: podman
    enabled: yes
    state: started

- name: Enable system podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    enabled: yes
    state: started

- name: Enable system pmlogger.service
  ansible.builtin.systemd:
    name: pmlogger.service
    enabled: yes
    state: started