---
- name: Enable libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Enable libvirtd.socket
  ansible.builtin.systemd:
    name: libvirtd.socket
    enabled: yes
    state: started

- name: Enable libvirtd-ro.socket
  ansible.builtin.systemd:
    name: libvirtd-ro.socket
    enabled: yes
    state: started

- name: Disable mcelog.service
  ansible.builtin.systemd:
    name: mcelog.service
    enabled: no
    state: stopped 